FROM node:19-alpine3.15

WORKDIR /view

COPY package.json ./

COPY tsconfig.json ./

COPY tsconfig.app.json ./

COPY tsconfig.spec.json ./

COPY . .

RUN npm install

EXPOSE 4200

CMD ["npm","run","start"]