version: "3.9"


services:
 database:
  image: postgres
  container_name: ngapp_database_postgres
  restart: unless-stopped
  hostname: postgresdb
  ports:
   - 5432:5432
  environment:
   - POSTGRES_USER=admin
   - POSTGRES_PASSWORD=admin
  volumes:
   - postgres-data:/var/lib/postgresql/data
  network_mode: host

 service:
  build: ./backEnd
  container_name: ngapp_backend
  network_mode: host
  depends_on:
   - database
  ports:
   - 3333:3333
  volumes:
   - .:/app
volumes:
 postgres-data: